os:
  - linux
  - osx
osx_image: xcode11.6
language: node_js
node_js:
  - '10'
  - '12'
  - '14'
before_install:
  - 'if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install vcbuildtools; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then npm config set msvs_version 2015 --global; fi'
before_script:
  - export NPMVERSION=$(echo "$($(which npm) -v)"|cut -c1)
  - 'if [[ $NPMVERSION == 5 ]]; then npm install -g npm@5; fi'
  - npm -v
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export export CXX=g++-6; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install socat; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod +x ./cc-test-reporter; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./cc-test-reporter before-build; fi'
after_success:
  - sed -i "s|tmp/node_modules/iobroker.nut/||" ./coverage/lcov.info
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -r 6acc760d8174dccb48942e7360fba89583b002166fb79bdfb7b87576fd1619ba; fi'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - socat
