/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Devices": {                                     "en": "Devices",                                         "de": "Geräte",                                          "ru": "Устройства",                                      "pt": "Dispositivos",                                    "nl": "Apparaten",                                       "fr": "Dispositifs",                                     "it": "Dispositivi",                                     "es": "Dispositivos",                                    "pl": "Pomysłowość",                                     "zh-cn": "设备"},
    "Force energy unit to kWh": {                    "en": "Force energy unit to kWh",                        "de": "Energieeinheit auf kWh setzen",                   "ru": "Измерять энергию в кВтч",                         "pt": "Força a unidade de energia para kWh",             "nl": "Forceer energie-eenheid naar kWh",                "fr": "Force énergie en kWh",                            "it": "Forza unità di energia a kWh",                    "es": "Unidad de energía de fuerza a kWh.",              "pl": "Wymuś jednostkę energii na kWh",                  "zh-cn": "强制能量单位为千瓦时"},
    "Found %s devices. Added %s new devices.": {     "en": "Found %s devices. Added %s new devices.",         "de": "Gefunden %s Geräte. %s neue Geräte hinzugefügt.", "ru": "Найдено %s устройств. Добавлено %s новых устройств.", "pt": "Encontrados %s dispositivos. Adicionado %s novos dispositivos.", "nl": "%s apparaten gevonden. %s nieuwe apparaten toegevoegd.", "fr": "Trouvé %s appareils. Ajout de %s nouveaux périphériques.", "it": "Trovato dispositivi di %s. Aggiunti %s nuovi dispositivi.", "es": "Encontrado %s dispositivos. Se agregaron %s nuevos dispositivos.", "pl": "Znaleziono urządzenia %s. Dodano %s nowych urządzeń.", "zh-cn": "找到％s个设备。"},
    "Found %s devices. Nothing new.": {              "en": "Found %s devices. Nothing new.",                  "de": "Gefunden %s Geräte. Nichts Neues.",               "ru": "Найдено %s устройств. Ничего нового.",            "pt": "Encontrados %s dispositivos. Nada de novo.",      "nl": "%s apparaten gevonden. Niets nieuws.",            "fr": "Trouvé %s appareils. Rien de nouveau.",           "it": "Trovato dispositivi di %s. Niente di nuovo.",     "es": "Encontrado %s dispositivos. Nada nuevo.",         "pl": "Znaleziono urządzenia %s. Nic nowego.",           "zh-cn": "找到％s个设备。"},
    "ID": {                                          "en": "ID",                                              "de": "ID",                                              "ru": "ID",                                              "pt": "ID",                                              "nl": "ID",                                              "fr": "ID",                                              "it": "ID",                                              "es": "IDENTIFICACIÓN",                                  "pl": "ID",                                              "zh-cn": "ID"},
    "M-Bus adapter settings": {                      "en": "M-Bus adapter settings",                          "de": "M-Bus-Adaptereinstellungen",                      "ru": "Настройки адаптера M-Bus",                        "pt": "Configurações do adaptador M-Bus",                "nl": "M-Bus adapterinstellingen",                       "fr": "Paramètres de l'adaptateur M-Bus",                "it": "Impostazioni dell'adattatore M-Bus",              "es": "Configuración del adaptador M-Bus",               "pl": "Ustawienia adaptera M-Bus",                       "zh-cn": "M-Bus适配器设置"},
    "Master is inactive": {                          "en": "Master is inactive",                              "de": "Der Meister ist inaktiv",                         "ru": "Мастер неактивен",                                "pt": "O mestre está inativo",                           "nl": "Meester is inactief",                             "fr": "Le maître est inactif",                           "it": "Il maestro è inattivo",                           "es": "El maestro está inactivo",                        "pl": "Mistrz jest nieaktywny",                          "zh-cn": "主人不活跃"},
    "No devices found": {                            "en": "No devices found",                                "de": "Keine Geräte gefunden",                           "ru": "Не найдено ни одного устройства",                 "pt": "Nenhum dispositivo encontrado",                   "nl": "Geen apparaten gevonden",                         "fr": "Aucun périphérique trouvé",                       "it": "Nessun dispositivo trovato",                      "es": "No se encontraron dispositivos",                  "pl": "Nie znaleziono urządzeń",                         "zh-cn": "找不到设备"},
    "Not available": {                               "en": "Port list not available",                         "de": "Portliste nicht verfügbar",                       "ru": "Список портов недоступен",                        "pt": "Lista de portas não disponível",                  "nl": "Poortlijst niet beschikbaar",                     "fr": "Liste de ports non disponible",                   "it": "Elenco delle porte non disponibile",              "es": "Lista de puertos no disponible",                  "pl": "Lista portów niedostępna",                        "zh-cn": "端口列表不可用"},
    "Options": {                                     "en": "Settings",                                        "de": "Einstellungen",                                   "ru": "Настройки",                                       "pt": "Configurações",                                   "nl": "instellingen",                                    "fr": "Paramètres",                                      "it": "Impostazioni",                                    "es": "Configuraciones",                                 "pl": "Ustawienia",                                      "zh-cn": "设定值"},
    "Please wait till port list is loaded ...": {    "en": "Please wait till the port list is loaded …",      "de": "Bitte warten bis die Portliste geladen ist …",    "ru": "Пожалуйста, дождитесь загрузки списка портов ...", "pt": "Aguarde até a lista de portas ser carregada ...", "nl": "Even geduld tot de poortlijst is geladen ...",    "fr": "Veuillez patienter jusqu'à ce que la liste de ports soit chargée ...", "it": "Attendere il caricamento dell'elenco delle porte ...", "es": "Espere hasta que se cargue la lista de puertos ...", "pl": "Poczekaj, aż lista portów zostanie załadowana ...", "zh-cn": "请等待端口列表加载完毕..."},
    "Scan devices": {                                "en": "Scan devices",                                    "de": "Geräte scannen",                                  "ru": "Сканировать устройства",                          "pt": "Dispositivos de digitalização",                   "nl": "Apparaten scannen",                               "fr": "Appareils de numérisation",                       "it": "Scansione dei dispositivi",                       "es": "Escanear dispositivos",                           "pl": "Skanuj urządzenia",                               "zh-cn": "扫描装置"},
    "Select port": {                                 "en": "Select port",                                     "de": "Wählen Sie den Port aus",                         "ru": "Выбрать порт",                                    "pt": "Selecione a porta",                               "nl": "Selecteer poort",                                 "fr": "Sélectionnez un port",                            "it": "Seleziona porta",                                 "es": "Seleccionar puerto",                              "pl": "Wybierz port",                                    "zh-cn": "选择端口"},
    "The scan can last over one minute or even longer. Be patient...": {"en": "The scan can last over one minute or even longer. Be patient...", "de": "Der Scan kann länger als eine Minute dauern. Sei geduldig...", "ru": "Сканирование может длиться более одной минуты или даже дольше. Потерпи...", "pt": "A varredura pode durar mais de um minuto ou até mais. Seja paciente...", "nl": "De scan kan meer dan een minuut of zelfs langer duren. Wees geduldig...", "fr": "L'analyse peut durer plus d'une minute ou même plus longtemps. Sois patient...", "it": "La scansione può durare più di un minuto o anche più. Essere pazientare...", "es": "El escaneo puede durar más de un minuto o incluso más. Se paciente...", "pl": "Skanowanie może trwać ponad minutę lub nawet dłużej. Bądź cierpliwy...", "zh-cn": "扫描可能持续一分钟甚至更长的时间。"},
    "Update interval (sec)": {                       "en": "Update interval (sec)",                           "de": "Aktualisierungsintervall (Sek)",                  "ru": "Интервал обновления (сек)",                       "pt": "Intervalo de atualização (s)",                    "nl": "Update-interval (s)",                             "fr": "Intervalle de mise à jour (s)",                   "it": "Intervallo di aggiornamento (s)",                 "es": "Intervalo de actualización (s)",                  "pl": "Interwał aktualizacji (s)",                       "zh-cn": "更新间隔（秒）"},
    "Use custom Serial port path": {                 "en": "Set a custom serial port name",                   "de": "Benutzerdefinierten Namen für die serielle Schnittstelle angeben", "ru": "Установите пользовательское имя последовательного порта", "pt": "Defina um nome de porta serial personalizado",    "nl": "Stel een aangepaste seriële poortnaam in",        "fr": "Définir un nom de port série personnalisé",       "it": "Imposta un nome di porta seriale personalizzato", "es": "Establecer un nombre de puerto serie personalizado", "pl": "Ustaw niestandardową nazwę portu szeregowego",    "zh-cn": "设置自定义串口名称"},
    "customSerialPort": {                            "en": "Custom serial Port path",                         "de": "Benutzerdefinierter Pfad der seriellen Schnittstelle", "ru": "Пользовательский последовательный порт",          "pt": "Caminho da porta serial personalizado",           "nl": "Aangepast serieel poortpad",                      "fr": "Chemin du port série personnalisé",               "it": "Percorso della porta seriale personalizzata",     "es": "Ruta de puerto serie personalizada",              "pl": "Niestandardowa ścieżka portu szeregowego",        "zh-cn": "自定义串行端口路径"},
    "defaultUpdateInterval": {                       "en": "Default update interval (sec)",                   "de": "Standardaktualisierungsintervall (Sek)",          "ru": "Интервал обновления по умолчанию (сек)",          "pt": "Intervalo de atualização padrão (s)",             "nl": "Standaard update-interval (s)",                   "fr": "Intervalle de mise à jour par défaut (s)",        "it": "Intervallo di aggiornamento predefinito (s)",     "es": "Intervalo de actualización predeterminado (s)",   "pl": "Domyślny interwał aktualizacji (s)",              "zh-cn": "默认更新间隔（秒）"},
    "host": {                                        "en": "Gateway IP",                                      "de": "Gateway-IP",                                      "ru": "IP-адрес шлюза",                                  "pt": "IP do gateway",                                   "nl": "Gateway IP",                                      "fr": "Passerelle IP",                                   "it": "IP del gateway",                                  "es": "IP de acceso",                                    "pl": "Adres IP bramy",                                  "zh-cn": "网关IP"},
    "port": {                                        "en": "TCP Port",                                        "de": "TCP-Anschluss",                                   "ru": "Порт TCP",                                        "pt": "Porto TCP",                                       "nl": "TCP-poort",                                       "fr": "Port TCP",                                        "it": "Porta TCP",                                       "es": "Puerto TCP",                                      "pl": "Port TCP",                                        "zh-cn": "TCP端口"},
    "serialBaudRate": {                              "en": "Serial baud rate",                                "de": "Serielle Baudrate",                               "ru": "Скорость передачи",                               "pt": "Taxa de transmissão em série",                    "nl": "Seriële baudrate",                                "fr": "Vitesse de transmission en série",                "it": "Baud rate seriale",                               "es": "Velocidad en baudios en serie",                   "pl": "Szeregowa prędkość transmisji",                   "zh-cn": "串行波特率"},
    "serialPort": {                                  "en": "Serial port",                                     "de": "Serielle Schnittstelle",                          "ru": "Серийный порт",                                   "pt": "Porta serial",                                    "nl": "Seriële poort",                                   "fr": "Port série",                                      "it": "Porta seriale",                                   "es": "Puerto serial",                                   "pl": "Port szeregowy",                                  "zh-cn": "串行端口"},
    "tcpTimeout": {                                  "en": "Timeout",                                         "de": "Timeout",                                         "ru": "Тайм-аут",                                        "pt": "Tempo esgotado",                                  "nl": "Time-out",                                        "fr": "Temps libre",                                     "it": "Tempo scaduto",                                   "es": "Se acabó el tiempo",                              "pl": "Koniec czasu",                                    "zh-cn": "超时"},
};